Databases:
   CMUMOSI: /data/cmumosi/Raw/Audio/WAV_16000/Segmented/{uri}.wav
   MUSAN: /data/musan/noise/free-sound/{uri}.wav

Protocols:
   CMUMOSI:
      SpeakerDiarization:
         CMUMOSI:
           train:
              uri: ./train.lst
              annotation: ./train.rttm
           development:
              uri: ./development.lst
              annotation: ./development.rttm
           test:
              uri: ./test.lst
              annotation: ./test.rttm
   MUSAN:
      Collection:
         BackgroundNoise:
            uri: /data/musan/noise/free-sound/ANNOTATIONS